---
galaxy_info:
  role_name: k3s_node_maintenance
  author: sudo-kraken
  description: Automated OS patching and maintenance for K3s cluster nodes
  company: "sudo-kraken"
  license: MIT
  min_ansible_version: "2.20.1"
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal
        - jammy
    - name: Debian
      versions:
        - buster
        - bullseye
        - bookworm
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - "35"
        - "36"
        - "37"
  galaxy_tags:
    - k3s
    - kubernetes
    - maintenance
    - patching
    - updates
    - automation
    - cluster
    - devops

dependencies: []
